server:
  port: 9090

auth-service:
  url: http://localhost:9091/auth/validate

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: thisisalongpasswordforthejwttokenauthenticationyouarefreetoenter

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9091
          predicates:
            - Path=/auth/**
        - id: stock-items-service
          uri: http://localhost:9093
          predicates:
            - Path=/api/**
          filters:
            - name: JwtAuthenticationFilter
        - id: prediction-service
          uri: http://localhost:9092
          predicates:
            - Path=/api/predictions/**
          filters:
            - name: JwtAuthenticationFilter

      default-filters:
        - name: DedupeResponseHeader
          args:
            strategy: RETAIN_UNIQUE

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    mk.tradesense.gatewayservice.filters: DEBUG

